
services:
 php: 
    build:
        dockerfile: docker/php/Dockerfile
    volumes:
        - './src:/var/www/html'
  
 nginx:
    image: nginx:latest
    ports: 
      - 8084:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    
 mysql:
    image: mysql:8
    ports:
      - 3343:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9092:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306